### ISSUE TITLE
Partially broken subtitles at the end of Grune's quest

### ISSUE THREAD

**Issue by Kilicool64** [lifebottle/Tales-of-Legendia-Undub#1]
As I reported on Discord several months ago, the subtitles for the end of Grune's quest (a video that plays just before the credits) don't fully work. After a while, you get a broken line and then nothing more. Here's the screenshot I uploaded back then: https://cdn.discordapp.com/attachments/863928820209287188/1159993120872734800/image.png?ex=658f53c7&is=657cdec7&hm=04abb42d7251fac51ef617c00bb6d66bab760f07fa5d6f4b195c20f74e01e30a&

**Comment by Trixarian** [comment]
Fixed with the latest Release
